site_name: Rag Tool docs
theme:
  name: material

nav:
  - Home: index.md
  - Developer Tools:
      - Precommit Hooks: dev-tools/precommit.md
      - Python: dev-tools/python.md
      - Jq: dev-tools/jq.md
  - Tests:
      - Erster Test: tests/first_results.md
      - Testfragen: tests/fragen.md
  - Research:
      - Scraping: research/scraping.md
      - Data Quality: research/data_quality.md
      - Vectordb: research/vector_database.md
      