site_name: Rag Tool docs
theme:
  name: material

nav:
  - Home: index.md
  - Developer Tools:
      - Black: dev-tools/black.md
      - Commitizen: dev-tools/commitizen.md
      - Python: dev-tools/python.md
  - Tests:
      - Erster Test: tests/first_results.md
      