name: Code Style & Lint Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit-checks:
    name: Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
