name: black format reviewdog
on: [pull_request]

jobs:
  black-reviewdog:
    name: Black with Reviewdog Suggestions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install black reviewdog

      - name: Run Black and pipe to Reviewdog
        run: |
          black --check --diff . | reviewdog -f=diff \
            -name="black" \
            -reporter=github-pr-suggest \
            -filter-mode=diff_context \
            -fail-level=info
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
