name: Black Formatter Check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.py'

jobs:
  black-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Black with reviewdog
        uses: reviewdog/action-black@v3.22.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter:  github-pr-review
          level: warning
          workdir: "."
          black_args: ""
          verbose: "true"
          fail_on_error: true