name: Commitizen Check

on:
  pull_request:

jobs:
  commitizen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Run Commitizen check via reviewdog
        run: |
          cz check --rev-range origin/main... 2>&1 | tee result.txt
        continue-on-error: true

      - name: Report with reviewdog
        uses: reviewdog/action-setup@v1
      - run: |
          cat result.txt | reviewdog -efm="%f:%l:%c: %m" -name="Commitizen" -reporter=github-pr-review -level=error
