name: Markdown Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.md'

jobs:
  markdownlint:
    name: runner / markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run markdownlint via reviewdog
        uses: reviewdog/action-markdownlint@v0.26.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          fail_on_error: true
