name: Markdown Lint

on:
  pull_request:
    paths:
      - '**.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint via reviewdog
        uses: reviewdog/action-setup@v0.17.0
        with:
          reviewdog_version: latest
          reporter: github-pr-review
          tool_name: markdownlint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          markdownlint "**/*.md" --stdin < /dev/null | reviewdog -efm="%f:%l %m"
