name: Ruff Lint

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: pip install ruff

      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1.3.2
        with:
          reviewdog_version: latest
      
      - name: Run Ruff and report via reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ruff check . | reviewdog -f=ruff -name="ruff" -reporter=github-pr-review -level=warning

